name: Build and Deploy Cactus Site

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Wir wechseln auf Python 3.9 (kompatibel mit Cactus UND Ubuntu 24.04)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # Wir installieren Cactus
    - name: Install Cactus
      run: |
        python -m pip install --upgrade pip
        pip install cactus

    - name: Build Website
      run: |
        cactus build

    - name: SFTP Deploy to Webhost
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        local-dir: ./build/
        server-dir: ${{ secrets.SFTP_REMOTE_DIR }}
        # So aktiviert man SFTP bei dieser speziellen Action richtig:
        sftp: true
        port: 22